### ISSUE TITLE
Orchestrator run as a service instead of terminal

### ISSUE THREAD

**Issue by Ghitafjorback** [Basico-PS/AutomationOrchestrator#28] opened 2020-02-28 12:40 UTC
If possible at all, it would be cool if Orchestrator could run as a service instead of in terminal.

**Comment by mbalslow** [comment] 2020-05-12 13:38
Duplicate of https://github.com/Basico-PS/AutomationOrchestrator/issues/41 (solved by [this commit](https://github.com/Basico-PS/AutomationOrchestrator/commit/d2ddddedb42fd8a42368a08a9c17bacbb83da15f) and will be available in the upcoming [v0.3.5](https://github.com/Basico-PS/AutomationOrchestrator/releases/tag/v0.3.5))

**Closed as completed by mbalslow** 2020-05-12 13:38 UTC
Labels: duplicate
